# Generated by Django 5.1 on 2024-08-27 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
